{"name": "test_div_exception[a-3-TypeError]", "status": "passed", "parameters": [{"name": "number7", "value": "'a'"}, {"name": "number8", "value": "3"}, {"name": "exception1", "value": "'TypeError'"}], "start": 1584177260606, "stop": 1584177260606, "uuid": "16d00d99-b67c-46c9-a6d0-ca059040f4f1", "historyId": "8e0d6fcea81a884fc612f718c8571145", "testCaseId": "ebcec6de53c4427b77c6496a8ada2176", "fullName": "unit.test_py_test#test_div_exception", "labels": [{"name": "suite", "value": "TypeError数据组"}, {"name": "tag", "value": "error"}, {"name": "parentSuite", "value": "unit"}, {"name": "host", "value": "chloehandeMacBook-Pro.local"}, {"name": "thread", "value": "21269-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_py_test"}]}