{"name": "test_sum", "status": "failed", "statusDetails": {"message": "AssertionError: 4 != 3 : x=3 expection =3", "trace": "self = <unit.test_demo.TestDemo testMethod=test_sum>\n\n    def test_sum(self):\n        print(\"testsum\")\n        x = 1 + 2\n        print(x)\n>       self.assertEqual(4, x, f'x={x} expection =3')\nE       AssertionError: 4 != 3 : x=3 expection =3\n\nunit/test_demo.py:28: AssertionError"}, "attachments": [{"name": "stdout", "source": "17166bb5-bebd-43c3-b3b7-7c97a965c8e5-attachment.txt", "type": "text/plain"}], "start": 1584177260552, "stop": 1584177260552, "uuid": "e8b71ac4-2e2d-4a06-8e75-c4cccb7190f8", "historyId": "5390adf865abe5b81318f923b154e1f5", "testCaseId": "29216c7dc00751117849a4f95ff5904f", "fullName": "unit.test_demo.TestDemo#test_sum", "labels": [{"name": "parentSuite", "value": "unit"}, {"name": "suite", "value": "test_demo"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "chloehandeMacBook-Pro.local"}, {"name": "thread", "value": "21269-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_demo"}]}