{"name": "test_div_exception[3-a-TypeError]", "status": "passed", "parameters": [{"name": "number7", "value": "3"}, {"name": "number8", "value": "'a'"}, {"name": "exception1", "value": "'TypeError'"}], "start": 1584177260602, "stop": 1584177260602, "uuid": "01c7f388-446c-4ad8-b50d-bd797637251b", "historyId": "f625510a12cf966ea5865ce615c9af52", "testCaseId": "ebcec6de53c4427b77c6496a8ada2176", "fullName": "unit.test_py_test#test_div_exception", "labels": [{"name": "suite", "value": "TypeError数据组"}, {"name": "tag", "value": "error"}, {"name": "parentSuite", "value": "unit"}, {"name": "host", "value": "chloehandeMacBook-Pro.local"}, {"name": "thread", "value": "21269-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_py_test"}]}